apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hcm-platform
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - hcm.example.com
      secretName: hcm-platform-tls
  rules:
    - host: hcm.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: hcm-api
                port:
                  number: 3001
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hcm-web
                port:
                  number: 80
