apiVersion: v1
kind: Secret
metadata:
  name: hcm-platform-secrets
type: Opaque
stringData:
  DATABASE_URL: postgresql://hcm_admin:replace-me@postgres:5432/hcm_platform
  JWT_SECRET: replace-me
  ENCRYPTION_KEY_ID: replace-me
  SYSTEM_API_KEY: replace-me
  INTEGRATION_API_KEY: replace-me
  MFA_DEMO_CODE: ""
