/**
 * The 24-step command processing pipeline.
 *
 * Each step is numbered so that failures can be reported precisely
 * via {@link CommandError.stepFailed}.
 */
export enum CommandPipelineStep {
  AUTHENTICATE_ACTOR = 1,
  RESOLVE_TENANT = 2,
  VALIDATE_TENANT_MODULE_ENABLED = 3,
  VALIDATE_COMMAND_SCHEMA = 4,
  FAST_IDEMPOTENCY_LOOKUP = 5,
  BEGIN_TRANSACTION = 6,
  RESERVE_IDEMPOTENCY_KEY = 7,
  REJECT_SAME_KEY_DIFFERENT_HASH = 8,
  LOAD_AGGREGATE_WITH_LOCK = 9,
  VALIDATE_TENANT_SUBJECT_WORKER_ACCESS = 10,
  EVALUATE_HR_DATA_PRIVACY_FIELD_POLICY = 11,
  EVALUATE_COMMAND_AUTHORIZATION_ROLE_SCOPE = 12,
  EVALUATE_MANAGER_HRBP_RELATIONSHIP = 13,
  EVALUATE_WORKFLOW_GUARD_EXPECTED_STATE_VERSION_EFFECTIVE_DATE = 14,
  EVALUATE_LEGAL_HOLD_RETENTION_COUNTRY_LABOR_LAW_APPROVAL_STATE = 15,
  EVALUATE_SOD_POLICY = 16,
  PERFORM_DOMAIN_TRANSITION_THROUGH_AGGREGATE_METHOD = 17,
  WRITE_AUTHORITATIVE_STATE = 18,
  WRITE_TRANSITION_LEDGER = 19,
  WRITE_HR_AUDIT_RECORD = 20,
  WRITE_OUTBOX_EVENT = 21,
  STORE_IDEMPOTENCY_RESULT = 22,
  COMMIT_TRANSACTION = 23,
  RETURN_COMMAND_RESULT_WITH_ALLOWED_NEXT_ACTIONS_AND_FIELD_FILTERED_DATA = 24,
}
