apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hcm-ci

resources:
  - ../../base

images:
  - name: ghcr.io/your-org/hr-hcm-api
    newName: ghcr.io/ashour158/hr-hcm-api
    newTag: ci
  - name: ghcr.io/your-org/hr-hcm-web
    newName: ghcr.io/ashour158/hr-hcm-web
    newTag: ci

patches:
  - target:
      kind: Ingress
      name: hcm-platform
    patch: |-
      - op: replace
        path: /spec/tls/0/hosts/0
        value: hcm-ci.local
      - op: replace
        path: /spec/rules/0/host
        value: hcm-ci.local
