import type { HcmSetupConfig } from './hcm-setup.types.js';

const BOOTSTRAP_RUNTIME_POLICY_AREAS = [
  'EMPLOYEE_SETUP',
  'LEAVE',
  'ATTENDANCE',
  'PAYROLL',
  'ACCESS_GOVERNANCE',
  'COUNTRY_POLICY',
  'COMPLIANCE',
  'BENEFITS',
  'GLOBAL_HR',
  'DEI_ANALYTICS',
  'ENGAGEMENT',
] as const;

export const DEFAULT_HCM_SETUP: HcmSetupConfig = {
  genderOptions: [
    { code: 'FEMALE', value: 'FEMALE', label: 'Female', active: true },
    { code: 'MALE', value: 'MALE', label: 'Male', active: true },
    { code: 'NON_BINARY', value: 'NON_BINARY', label: 'Non-binary', active: true },
    { code: 'UNDISCLOSED', value: 'UNDISCLOSED', label: 'Prefer not to say', active: true },
  ],
  workPhoneEnabled: true,
  locations: [
    {
      code: 'CAIRO_HQ',
      label: 'Cairo HQ',
      active: true,
      countryCode: 'EG',
      countryName: 'Egypt',
      flag: 'EG',
      city: 'Cairo',
      currency: 'EGP',
      addressLine1: 'Nile Corniche',
      latitude: 30.0444,
      longitude: 31.2357,
    },
    {
      code: 'US_REMOTE',
      label: 'United States Remote',
      active: true,
      countryCode: 'US',
      countryName: 'United States',
      flag: 'US',
      city: 'New York',
      currency: 'USD',
    },
  ],
  cities: [
    { code: 'CAIRO', label: 'Cairo', active: true, countryCode: 'EG', flag: 'EG', currency: 'EGP' },
    { code: 'ALEXANDRIA', label: 'Alexandria', active: true, countryCode: 'EG', flag: 'EG', currency: 'EGP' },
    { code: 'NEW_YORK', label: 'New York', active: true, countryCode: 'US', flag: 'US', currency: 'USD' },
    { code: 'LONDON', label: 'London', active: true, countryCode: 'GB', flag: 'GB', currency: 'GBP' },
  ],
  departments: [
    { code: 'PEOPLE_OPS', label: 'People Operations', active: true },
    { code: 'FINANCE', label: 'Finance', active: true },
    { code: 'ENGINEERING', label: 'Engineering', active: true },
  ],
  jobTitles: [
    { code: 'HR_OPERATIONS_ANALYST', label: 'HR Operations Analyst', active: true },
    { code: 'HRBP', label: 'HR Business Partner', active: true },
    { code: 'PAYROLL_SPECIALIST', label: 'Payroll Specialist', active: true },
  ],
  employeeIdPolicy: {
    mode: 'MANUAL_ONLY',
  },
  socialMediaFields: [
    { code: 'LINKEDIN', label: 'LinkedIn', active: true },
    { code: 'PORTFOLIO', label: 'Portfolio', active: true },
    { code: 'FACEBOOK', label: 'Facebook', active: true },
    { code: 'INSTAGRAM', label: 'Instagram', active: true },
  ],
  documentRequirements: [
    {
      code: 'NATIONAL_ID',
      label: 'National ID',
      active: true,
      required: true,
      allowMultiple: false,
      acceptedMimeTypes: ['application/pdf', 'image/png', 'image/jpeg'],
    },
    {
      code: 'EDUCATION_CERTIFICATE',
      label: 'Education Certificate',
      active: true,
      required: true,
      allowMultiple: true,
      acceptedMimeTypes: ['application/pdf', 'image/png', 'image/jpeg'],
    },
    {
      code: 'EMPLOYMENT_CONTRACT',
      label: 'Employment Contract',
      active: true,
      required: false,
      allowMultiple: false,
      acceptedMimeTypes: ['application/pdf'],
    },
  ],
  fieldRules: [
    { fieldKey: 'firstName', label: 'First Name', section: 'Identity', required: true, active: true },
    { fieldKey: 'lastName', label: 'Last Name', section: 'Identity', required: true, active: true },
    { fieldKey: 'personalEmail', label: 'Personal Email', section: 'Identity', required: false, active: true },
    { fieldKey: 'workEmail', label: 'Work Email', section: 'Identity', required: true, active: true },
    { fieldKey: 'phoneNumber', label: 'Personal Phone', section: 'Identity', required: false, active: true },
    { fieldKey: 'workPhoneNumber', label: 'Work Phone', section: 'Identity', required: false, active: true },
    { fieldKey: 'department', label: 'Department', section: 'Organization', required: true, active: true },
    { fieldKey: 'jobTitle', label: 'Job Title', section: 'Organization', required: false, active: true },
    { fieldKey: 'workAuthorization', label: 'Work Authorization', section: 'Compliance', required: false, active: true },
    { fieldKey: 'taxProfile', label: 'Payroll Tax Identifiers', section: 'Payroll', required: false, active: true },
    { fieldKey: 'bankAccount', label: 'Bank Account', section: 'Payroll', required: false, active: true },
    { fieldKey: 'dependents', label: 'Benefits Dependents', section: 'Benefits', required: false, active: true },
    { fieldKey: 'beneficiaries', label: 'Beneficiaries', section: 'Benefits', required: false, active: true },
    { fieldKey: 'assets', label: 'Assets and Devices', section: 'IT Access', required: false, active: true },
    { fieldKey: 'skills', label: 'Skills', section: 'Talent', required: false, active: true },
    { fieldKey: 'consents', label: 'Consents and Privacy Notices', section: 'Governance', required: false, active: true },
    { fieldKey: 'employmentContract', label: 'Employment Contract', section: 'Documents', required: false, active: true },
  ],
  leavePolicies: [
    {
      code: 'VACATION',
      label: 'Annual leave',
      active: true,
      unit: 'DAYS',
      paid: true,
      deductFromBalance: true,
      requestableByEmployee: true,
      payrollImpact: 'PAID_LEAVE',
      approvalWorkflow: 'MANAGER',
      annualEntitlement: 21,
      maxPerRequest: 15,
      allowHalfDay: true,
      minNoticeDays: 2,
      periodLimits: [
        {
          code: 'VACATION_MONTHLY_DAYS',
          label: 'Monthly annual leave limit',
          active: true,
          window: 'CALENDAR_MONTH',
          maxAmount: 10,
          includeStatuses: ['PENDING_APPROVAL', 'APPROVED'],
        },
      ],
    },
    {
      code: 'SICK',
      label: 'Sick leave',
      active: true,
      unit: 'DAYS',
      paid: true,
      deductFromBalance: true,
      requestableByEmployee: true,
      payrollImpact: 'PAID_LEAVE',
      approvalWorkflow: 'MANAGER',
      annualEntitlement: 14,
      maxPerRequest: 7,
      allowHalfDay: false,
      requiresDocumentAfter: 2,
    },
    {
      code: 'PERSONAL',
      label: 'Personal leave',
      active: true,
      unit: 'DAYS',
      paid: true,
      deductFromBalance: true,
      requestableByEmployee: true,
      payrollImpact: 'PAID_LEAVE',
      approvalWorkflow: 'MANAGER',
      annualEntitlement: 3,
      maxPerRequest: 2,
      allowHalfDay: true,
    },
    {
      code: 'UNPAID',
      label: 'Unpaid leave',
      active: true,
      unit: 'DAYS',
      paid: false,
      deductFromBalance: false,
      requestableByEmployee: true,
      payrollImpact: 'UNPAID_LEAVE',
      approvalWorkflow: 'MANAGER_THEN_HR',
      maxPerRequest: 30,
    },
    {
      code: 'PERMISSION',
      label: 'Permission',
      active: true,
      unit: 'HOURS',
      paid: true,
      deductFromBalance: true,
      requestableByEmployee: true,
      payrollImpact: 'PERMISSION',
      approvalWorkflow: 'MANAGER',
      annualEntitlement: 24,
      maxPerRequest: 4,
      periodLimits: [
        {
          code: 'PERMISSION_WEEKLY_REQUESTS',
          label: 'Weekly permission request limit',
          active: true,
          window: 'CALENDAR_WEEK',
          maxRequests: 2,
          includeStatuses: ['PENDING_APPROVAL', 'APPROVED'],
        },
        {
          code: 'PERMISSION_MONTHLY_HOURS',
          label: 'Monthly permission hours limit',
          active: true,
          window: 'CALENDAR_MONTH',
          maxAmount: 8,
          includeStatuses: ['PENDING_APPROVAL', 'APPROVED'],
        },
      ],
    },
    {
      code: 'PUBLIC_HOLIDAY',
      label: 'Public holiday',
      active: true,
      unit: 'DAYS',
      paid: true,
      deductFromBalance: false,
      requestableByEmployee: false,
      systemManaged: true,
      payrollImpact: 'NO_PAYROLL_IMPACT',
      approvalWorkflow: 'AUTO_APPROVE',
    },
  ],
  payrollCalculationPolicy: {
    taxMode: 'FLAT_PERCENT',
    taxRatePercent: 15,
    employeeInsuranceRatePercent: 7,
    employerInsuranceRatePercent: 12,
  },
  statutoryPayrollPacks: [
    {
      code: 'EG_2026',
      label: 'Egypt statutory payroll 2026',
      active: true,
      countryCode: 'EG',
      locationCodes: ['CAIRO_HQ'],
      employeeTypes: ['FULL_TIME', 'PERMANENT'],
      currency: 'EGP',
      effectiveFrom: '2026-01-01',
      calculationPolicy: {
        taxMode: 'PROGRESSIVE_BRACKETS',
        taxRatePercent: 0,
        taxBrackets: [
          { code: 'EG_EXEMPT', label: 'Egypt exempt band', thresholdFrom: 0, thresholdTo: 5000, ratePercent: 0 },
          { code: 'EG_STANDARD', label: 'Egypt standard band', thresholdFrom: 5000, ratePercent: 20 },
        ],
        employeeInsuranceRatePercent: 7,
        employerInsuranceRatePercent: 12,
        employeeInsuranceCap: 1200,
        employerInsuranceCap: 2000,
      },
      glAccountMapping: {
        salaryExpenseAccount: '6000',
        employerInsuranceExpenseAccount: '6010',
        taxPayableAccount: '2100',
        insurancePayableAccount: '2110',
        deductionPayableAccount: '2200',
        bankClearingAccount: '1000',
      },
      bankFileFormats: ['CSV', 'CBE_EGYPT_CSV'],
    },
  ],
  attendancePolicy: {
    standardDailyMinutes: 480,
    flexibleHoursEnabled: true,
    flexibleWindowStart: '07:00',
    flexibleWindowEnd: '10:00',
    coreStartTime: '10:00',
    coreEndTime: '15:00',
    standardStartTime: '09:00',
    standardEndTime: '17:00',
    lateGraceMinutes: 15,
    overtimeAfterMinutes: 480,
    geofenceEnabled: true,
    allowedRadiusMeters: 250,
    timezoneOffsetMinutes: 180,
    workDays: [0, 1, 2, 3, 4],
    holidays: [
      { date: '2026-05-26', name: 'Eid Al-Adha' },
      { date: '2026-05-27', name: 'Eid Al-Adha' },
      { date: '2026-05-28', name: 'Eid Al-Adha' },
      { date: '2026-05-29', name: 'Eid Al-Adha' },
      { date: '2026-05-30', name: 'Eid Al-Adha' },
    ],
    roundingIncrementMinutes: 5,
    unpaidBreakMinutes: 0,
    missingCheckoutBlocksPayroll: true,
    duplicatePunchBlocksPayroll: true,
    lowTrustPunchBlocksPayroll: true,
    minClockTrustScore: 70,
    minimumPayableDayMinutes: 240,
    shiftRotations: [
      {
        code: 'CAIRO_OPS_4_DAY',
        label: 'Cairo operations 4-day rotation',
        active: true,
        anchorDate: '2026-05-25',
        cycleDays: 4,
        workDayOffsets: [0, 1],
        dailyMinutes: 720,
        startTime: '07:00',
        endTime: '19:00',
        locationCodes: ['CAIRO_HQ'],
      },
    ],
    geofenceProfiles: [
      {
        code: 'CAIRO_HQ_STRICT',
        label: 'Cairo HQ strict geofence',
        active: true,
        locationCode: 'CAIRO_HQ',
        radiusMeters: 250,
        highAccuracyRequiredMeters: 100,
        requireGeolocation: true,
        blockOutsideGeofence: true,
      },
    ],
    deviceTrustRules: [
      { code: 'BROWSER_DEVICES', label: 'Browser attendance devices', active: true, deviceIdPattern: 'browser*', trustLevel: 'STANDARD' },
      { code: 'CORRECTION_DEVICE', label: 'Manager correction source', active: true, deviceIdPattern: 'attendance-correction', trustLevel: 'TRUSTED' },
    ],
    flexibleHoursRules: [
      {
        code: 'CAIRO_CORE_HOURS',
        label: 'Cairo core hours',
        active: true,
        locationCodes: ['CAIRO_HQ'],
        flexibleWindowStart: '07:00',
        flexibleWindowEnd: '10:00',
        coreStartTime: '10:00',
        coreEndTime: '15:00',
        minimumPayableDayMinutes: 240,
      },
    ],
    holidayCalendars: [
      { date: '2026-05-26', name: 'Eid Al-Adha', countryCode: 'EG' },
      { date: '2026-05-27', name: 'Eid Al-Adha', countryCode: 'EG' },
      { date: '2026-05-28', name: 'Eid Al-Adha', countryCode: 'EG' },
      { date: '2026-05-29', name: 'Eid Al-Adha', countryCode: 'EG' },
      { date: '2026-05-30', name: 'Eid Al-Adha', countryCode: 'EG' },
    ],
  },
  earningPolicies: [
    {
      code: 'TRANSPORT_ALLOWANCE',
      label: 'Transport allowance',
      active: true,
      type: 'FIXED_AMOUNT',
      amount: 0,
      taxable: false,
      insurable: false,
      recurring: true,
    },
    {
      code: 'OVERTIME_PREMIUM',
      label: 'Overtime premium',
      active: true,
      type: 'LOGIC_LEDGER',
      taxable: true,
      insurable: true,
      recurring: true,
      logicLedger: {
        code: 'OVERTIME_HOURS',
        source: 'ATTENDANCE_LEDGER',
        base: 'ATTENDANCE_OVERTIME_HOURS',
        method: 'PER_UNIT',
        amount: 0,
        monthlyCap: 0,
        posting: {
          payslipLineType: 'OVERTIME_EARNING',
          glAccount: '6100',
        },
        retroBehavior: 'RECALCULATE_OPEN_PERIODS',
      },
    },
  ],
  deductionPolicies: [
    {
      code: 'LATE_PER_MINUTE',
      label: 'Late arrival deduction',
      active: true,
      type: 'LOGIC_LEDGER',
      timing: 'POST_TAX',
      logicLedger: {
        code: 'LATE_MINUTES',
        source: 'ATTENDANCE_LEDGER',
        base: 'ATTENDANCE_LATE_MINUTES',
        method: 'PER_UNIT',
        amount: 2,
        monthlyCap: 1500,
        posting: {
          payslipLineType: 'LATE_DEDUCTION',
          glAccount: '2200',
        },
        retroBehavior: 'ADJUSTMENT_QUEUE',
      },
    },
    {
      code: 'UNDERTIME_PER_MINUTE',
      label: 'Undertime deduction',
      active: true,
      type: 'LOGIC_LEDGER',
      timing: 'POST_TAX',
      logicLedger: {
        code: 'UNDERTIME_MINUTES',
        source: 'ATTENDANCE_LEDGER',
        base: 'ATTENDANCE_UNDERTIME_MINUTES',
        method: 'PER_UNIT',
        amount: 2,
        monthlyCap: 1500,
        posting: {
          payslipLineType: 'UNDERTIME_DEDUCTION',
          glAccount: '2200',
        },
        retroBehavior: 'ADJUSTMENT_QUEUE',
      },
    },
  ],
  payrollBlockingRules: [
    {
      code: 'DUPLICATE_PAYROLL_CYCLE',
      label: 'Duplicate payroll cycle',
      active: true,
      condition: 'DUPLICATE_PAYROLL_CYCLE',
      severity: 'ERROR',
      blocking: true,
    },
    {
      code: 'MISSING_BANK_ACCOUNT',
      label: 'Missing bank account',
      active: true,
      condition: 'MISSING_BANK_ACCOUNT',
      severity: 'ERROR',
      blocking: true,
    },
    {
      code: 'MISSING_PAYROLL_COMPENSATION',
      label: 'Missing payroll compensation',
      active: true,
      condition: 'MISSING_PAYROLL_COMPENSATION',
      severity: 'ERROR',
      blocking: true,
    },
    {
      code: 'ATTENDANCE_BLOCKER',
      label: 'Unresolved attendance blocker',
      active: true,
      condition: 'ATTENDANCE_BLOCKER',
      severity: 'ERROR',
      blocking: true,
    },
    {
      code: 'ZERO_OR_NEGATIVE_NET_PAY',
      label: 'Zero or negative net pay',
      active: true,
      condition: 'ZERO_OR_NEGATIVE_NET_PAY',
      severity: 'ERROR',
      blocking: true,
    },
    {
      code: 'MISSING_TAX_IDENTIFIER',
      label: 'Missing tax identifier',
      active: true,
      condition: 'MISSING_TAX_IDENTIFIER',
      severity: 'ERROR',
      blocking: true,
    },
    {
      code: 'MISSING_POLICY_ASSIGNMENT',
      label: 'Missing payroll policy assignment',
      active: true,
      condition: 'MISSING_POLICY_ASSIGNMENT',
      severity: 'WARNING',
      blocking: false,
    },
    {
      code: 'COUNTRY_POLICY_STALE',
      label: 'Country statutory policy is missing or stale',
      active: true,
      condition: 'COUNTRY_POLICY_STALE',
      severity: 'ERROR',
      blocking: true,
    },
  ],
  countryPolicyRuntime: {
    countryCode: 'EG',
    packVersion: 'SYSTEM_BOOTSTRAP_2026',
    blocksPayrollIfStale: true,
    effectiveFrom: '2026-01-01',
    effectiveUntil: '2026-12-31',
  },
  compliancePolicyRuntime: {
    acknowledgementRequired: true,
    acknowledgementDueDays: 14,
    policyFamily: 'SYSTEM_BOOTSTRAP',
    acknowledgementRules: [{
      code: 'STANDARD_ACK',
      label: 'Standard acknowledgement',
      active: true,
      outcomes: [{ action: 'CREATE_ACKNOWLEDGEMENT', reason: 'Employee-facing policy requires acknowledgement.' }],
      retroBehavior: 'REVALIDATE_PENDING',
    }],
    retentionRules: [{
      code: 'STANDARD_RETENTION',
      label: 'Standard retention',
      active: true,
      outcomes: [{ action: 'CREATE_NOTIFICATION', value: { retentionClass: 'STANDARD' }, reason: 'Compliance records inherit standard retention.' }],
      retroBehavior: 'FUTURE_ONLY',
    }],
  },
  benefitsPolicyRuntime: {
    eligibilityRules: [{
      code: 'MEDICAL_FULL_TIME',
      label: 'Medical plan full-time eligibility',
      active: true,
      conditions: [{ field: 'employmentType', operator: 'IN', value: ['FULL_TIME', 'PERMANENT'] }],
      outcomes: [{ action: 'ALLOW', reason: 'Eligible for medical plan enrollment.' }],
      retroBehavior: 'REVALIDATE_PENDING',
    }],
    enrollmentWindowRules: [{
      code: 'NEW_HIRE_30_DAYS',
      label: 'New hire enrollment window',
      active: true,
      outcomes: [{ action: 'REQUIRE_APPROVAL', value: { windowDays: 30 }, reason: 'New hires can enroll during their first 30 days.' }],
      retroBehavior: 'FUTURE_ONLY',
    }],
    payrollBridgeRules: [{
      code: 'MEDICAL_EMPLOYEE_SHARE',
      label: 'Medical employee contribution bridge',
      active: true,
      outcomes: [{ action: 'CREATE_PAYROLL_BRIDGE', value: { deductionCode: 'MEDICAL_EMPLOYEE_SHARE' }, reason: 'Approved coverage creates payroll contribution input.' }],
      retroBehavior: 'ADJUSTMENT_QUEUE',
    }],
  },
  globalHrPolicyRuntime: {
    workAuthorizationRules: [{
      code: 'WORK_AUTH_ACTIVE_REQUIRED',
      label: 'Active work authorization required',
      active: true,
      outcomes: [{ action: 'REQUIRE_APPROVAL', reason: 'Work authorization changes require HR validation before employment-impacting actions.' }],
      retroBehavior: 'REVALIDATE_PENDING',
    }],
    worksCouncilRules: [{
      code: 'WORKS_COUNCIL_REVIEW',
      label: 'Works council review',
      active: true,
      outcomes: [{ action: 'REQUIRE_APPROVAL', reason: 'Country-specific consultation is required when policy scope matches.' }],
      retroBehavior: 'BLOCK_RETROACTIVE',
    }],
    statutoryLeaveBridgeRules: [{
      code: 'STATUTORY_LEAVE_BRIDGE',
      label: 'Statutory leave bridge',
      active: true,
      outcomes: [{ action: 'CREATE_REVALIDATION', reason: 'Country statutory leave setup revalidates open leave rules.' }],
      retroBehavior: 'REVALIDATE_PENDING',
    }],
  },
  deiAnalyticsPolicyRuntime: {
    suppressionRules: [{
      code: 'SMALL_SEGMENT_SUPPRESSION',
      label: 'Small segment suppression',
      active: true,
      outcomes: [{ action: 'BLOCK', value: { minimumPopulation: 10 }, reason: 'Small population analytics are suppressed for privacy.' }],
      retroBehavior: 'FUTURE_ONLY',
    }],
    payEquityReviewRules: [{
      code: 'PAY_EQUITY_REVIEW_REQUIRED',
      label: 'Pay equity review required',
      active: true,
      outcomes: [{ action: 'REQUIRE_APPROVAL', reason: 'Pay equity findings require review before publication.' }],
      retroBehavior: 'REVALIDATE_PENDING',
    }],
    remediationRules: [{
      code: 'REMEDIATION_TRACKING_REQUIRED',
      label: 'Remediation tracking required',
      active: true,
      outcomes: [{ action: 'CREATE_NOTIFICATION', reason: 'Approved remediation plans notify accountable owners.' }],
      retroBehavior: 'FUTURE_ONLY',
    }],
  },
  engagementPolicyRuntime: {
    surveyPublicationRules: [{
      code: 'SURVEY_PUBLICATION_APPROVAL',
      label: 'Survey publication approval',
      active: true,
      outcomes: [{ action: 'REQUIRE_APPROVAL', reason: 'Engagement surveys require approval before publication.' }],
      retroBehavior: 'FUTURE_ONLY',
    }],
    responsePrivacyRules: [{
      code: 'ANONYMOUS_RESPONSE_PRIVACY',
      label: 'Anonymous response privacy',
      active: true,
      outcomes: [{ action: 'MASK_FIELD', reason: 'Anonymous survey responses mask employee identifiers in analytics views.' }],
      retroBehavior: 'FUTURE_ONLY',
    }],
    recognitionApprovalRules: [{
      code: 'RECOGNITION_APPROVAL_REQUIRED',
      label: 'Recognition approval required',
      active: true,
      outcomes: [{ action: 'REQUIRE_APPROVAL', reason: 'Recognition awards require manager or HR approval before award.' }],
      retroBehavior: 'REVALIDATE_PENDING',
    }],
  },
  runtimePolicyRevisions: BOOTSTRAP_RUNTIME_POLICY_AREAS.map((area) => ({
    area,
    revisionId: `SYSTEM_BOOTSTRAP_${area}`,
    status: 'APPLIED',
    appliedAt: '2026-01-01T00:00:00.000Z',
    engineName: 'BootstrapPolicyRuntime',
    engineVersion: '1.0.0',
  })),
};
