export type CommercialModuleMaturity = 'native-ui' | 'workbench' | 'api-ready';

export interface CommercialModule {
  id: string;
  label: string;
  category: 'Core HR' | 'Workforce' | 'Payroll & Reward' | 'Talent' | 'Compliance' | 'Operations';
  maturity: CommercialModuleMaturity;
  backendRoot: string;
  nativePath?: string;
  summary: string;
  personas: string[];
  builtCapabilities: string[];
  keyWorkflows: string[];
  dataObjects: string[];
  governance: string[];
  commercialNext: string[];
}

export function moduleOperationsPath(id: string) {
  return `/admin/modules/${id}/operations`;
}

export const commercialModules: CommercialModule[] = [
  {
    id: 'employees',
    label: 'Employee Core',
    category: 'Core HR',
    maturity: 'native-ui',
    backendRoot: '/hr/core',
    nativePath: '/admin/employees',
    summary: 'Employee profile, employment relationship, job assignment, contracts, personal data, and lifecycle states.',
    personas: ['Employee', 'Manager', 'HR Admin', 'Payroll Admin'],
    builtCapabilities: ['Create employee', 'Activate employee', 'Assign job', 'Profile governance', 'Allowed lifecycle actions'],
    keyWorkflows: ['Hire to active employee', 'Employee profile maintenance', 'Job assignment to payroll eligibility'],
    dataObjects: ['Employee profile', 'Employment relationship', 'Job assignment', 'Employment contract', 'Personal data record'],
    governance: ['Duplicate prevention', 'Special category data controls', 'Field access policy', 'Audit trail'],
    commercialNext: ['Make employee profile the master source for benefits, payroll, assets, skills, and documents.'],
  },
  {
    id: 'organization',
    label: 'Organization',
    category: 'Core HR',
    maturity: 'native-ui',
    backendRoot: '/organization',
    nativePath: '/admin/organization',
    summary: 'Legal entities, departments, org units, manager relationships, reporting lines, and hierarchy context.',
    personas: ['HR Admin', 'Manager', 'Employee'],
    builtCapabilities: ['Legal entities', 'Org units', 'Manager chain', 'Department lookup'],
    keyWorkflows: ['Build org chart', 'Assign employee to department', 'Resolve manager approvals'],
    dataObjects: ['Legal entity', 'Org unit', 'Manager relationship'],
    governance: ['Hierarchy-based visibility', 'Approval routing', 'Tenant isolation'],
    commercialNext: ['Add live drag-and-drop org chart management and position-based reporting overlays.'],
  },
  {
    id: 'position-control',
    label: 'Position Control',
    category: 'Core HR',
    maturity: 'native-ui',
    backendRoot: '/position-control',
    nativePath: '/admin/workforce-planning',
    summary: 'Position, headcount request, approval, opening, filling, freezing, and closure governance.',
    personas: ['HR Admin', 'Finance', 'Manager'],
    builtCapabilities: ['Position lifecycle', 'Headcount requests', 'SoD-aware approval flow'],
    keyWorkflows: ['Request headcount', 'Approve position', 'Fill position from employee assignment'],
    dataObjects: ['Position', 'Headcount request'],
    governance: ['Budget ownership', 'Segregation of duties', 'Position status FSM'],
    commercialNext: ['Expose workforce planning board with budget, vacancy, and requisition links.'],
  },
  {
    id: 'attendance',
    label: 'Attendance',
    category: 'Workforce',
    maturity: 'native-ui',
    backendRoot: '/time/attendance',
    nativePath: '/admin/attendance',
    summary: 'Clock events, geolocation evidence, daily ledger, exceptions, reminders, corrections, timesheets, and payroll handoff.',
    personas: ['Employee', 'Manager', 'HR Admin', 'Payroll Admin'],
    builtCapabilities: ['Check-in/out', 'Geolocation stamping', 'Ledger finalization', 'Correction queue', 'Timesheet generation', 'Attendance exports'],
    keyWorkflows: ['Employee check-in to daily ledger', 'Manager correction approval', 'Period close to payroll input'],
    dataObjects: ['Clock event', 'Daily ledger', 'Timesheet', 'Attendance exception', 'Correction request', 'Overtime approval'],
    governance: ['Self/team/admin scope', 'Geofence evidence', 'Device trust', 'Payroll close blockers'],
    commercialNext: ['Add mobile-grade device identity, biometric adapters, shift bids, and attendance anomaly scoring.'],
  },
  {
    id: 'leave',
    label: 'Leave',
    category: 'Workforce',
    maturity: 'native-ui',
    backendRoot: '/absence/leave',
    nativePath: '/admin/leave',
    summary: 'Leave requests, leave cases, accrual balances, entitlement calculations, public holiday policy, and manager approvals.',
    personas: ['Employee', 'Manager', 'HR Admin', 'Payroll Admin'],
    builtCapabilities: ['Day-based leave policies', 'Hourly permission policies', 'Manager approval', 'Balance display', 'Payroll impact'],
    keyWorkflows: ['Employee leave request', 'Manager approve/reject', 'Policy-driven duration and balance impact'],
    dataObjects: ['Leave request', 'Leave case', 'Accrual balance', 'Entitlement calculation', 'Leave policy'],
    governance: ['Manager hierarchy', 'Policy units', 'Holiday exclusion', 'Payroll impact classification'],
    commercialNext: ['Finish admin leave calendar, accrual runs, carryover, encashment, blackout days, and team calendar.'],
  },
  {
    id: 'workforce-management',
    label: 'Workforce Management',
    category: 'Workforce',
    maturity: 'native-ui',
    backendRoot: '/workforce-management',
    nativePath: '/admin/workforce-management',
    summary: 'Shift schedules, open shifts, shift bids, swaps, coverage gaps, and staffing execution.',
    personas: ['Scheduler', 'Manager', 'Employee'],
    builtCapabilities: ['Shift schedule lifecycle', 'Open shift bidding', 'Swap request governance', 'Coverage gap tracking'],
    keyWorkflows: ['Publish schedule', 'Bid for shift', 'Approve swap', 'Resolve coverage gap'],
    dataObjects: ['Shift schedule', 'Open shift', 'Shift bid', 'Swap request', 'Coverage gap'],
    governance: ['Eligibility', 'Manager approval', 'Coverage risk', 'Audit events'],
    commercialNext: ['Create scheduler grid with drag/drop shifts, staffing demand, and fatigue rules.'],
  },
  {
    id: 'payroll',
    label: 'Payroll',
    category: 'Payroll & Reward',
    maturity: 'native-ui',
    backendRoot: '/payroll',
    nativePath: '/admin/payroll',
    summary: 'Monthly payroll cycle, deduction policies, attendance inputs, blocking rules, calculation, payslips, bank file, GL posting, and exports.',
    personas: ['Payroll Admin', 'HR Admin', 'Employee', 'Finance'],
    builtCapabilities: ['Cycle creation', 'Policy assignment', 'Net salary calculation', 'Bank export', 'Payslip publish', 'GL posting'],
    keyWorkflows: ['Attendance close to payroll input', 'Payroll calculation to review', 'Approve and publish payslips', 'Bank file export'],
    dataObjects: ['Payroll cycle', 'Payroll input', 'Calculation run', 'Result line', 'Payment batch', 'Payslip', 'GL posting'],
    governance: ['Salary self-only visibility', 'Payroll blockers', 'SoD approval', 'Bank data protection'],
    commercialNext: ['Add country statutory packs, retro payroll, loan schedules, garnishments, and reconciliation dashboards.'],
  },
  {
    id: 'compensation',
    label: 'Compensation',
    category: 'Payroll & Reward',
    maturity: 'native-ui',
    backendRoot: '/compensation',
    nativePath: '/admin/compensation',
    summary: 'Comp plans, bands, pay changes, bonus cycles, equity grants, variable compensation, and total reward statements.',
    personas: ['Compensation Admin', 'Manager', 'HR Admin', 'Employee'],
    builtCapabilities: ['Comp plan lifecycle', 'Band governance', 'Pay change workflow', 'Bonus and equity objects'],
    keyWorkflows: ['Propose pay change', 'Approve comp change', 'Generate total compensation statement'],
    dataObjects: ['Comp plan', 'Comp band', 'Comp change', 'Bonus cycle', 'Equity grant', 'Total compensation statement'],
    governance: ['Salary visibility', 'Approval chains', 'Pay equity link', 'Audit history'],
    commercialNext: ['Expose compensation review worksheet, merit matrix, and budget simulation.'],
  },
  {
    id: 'benefits',
    label: 'Benefits',
    category: 'Payroll & Reward',
    maturity: 'native-ui',
    backendRoot: '/benefits',
    nativePath: moduleOperationsPath('benefits'),
    summary: 'Benefit programs, enrollment, life events, spending accounts, dependents, beneficiaries, and carrier reconciliation.',
    personas: ['Employee', 'Benefits Admin', 'Payroll Admin'],
    builtCapabilities: ['Program lifecycle', 'Enrollment objects', 'Life event handling', 'Carrier reconciliation model'],
    keyWorkflows: ['Enroll in benefits', 'Process life event', 'Send deductions to payroll', 'Reconcile carrier file'],
    dataObjects: ['Benefits program', 'Enrollment', 'Life event', 'Spending account', 'Carrier reconciliation'],
    governance: ['Eligibility', 'Evidence documents', 'Dependent/beneficiary privacy', 'Payroll deduction handoff'],
    commercialNext: ['Build enrollment wizard, evidence upload, plan comparison, and carrier file import/export.'],
  },
  {
    id: 'recruiting',
    label: 'Recruiting',
    category: 'Talent',
    maturity: 'native-ui',
    backendRoot: '/hr/recruiting',
    nativePath: '/admin/recruiting',
    summary: 'Job requisitions, candidates, interviews, offers, approvals, publishing, and offer acceptance.',
    personas: ['Recruiter', 'Hiring Manager', 'HR Admin', 'Candidate'],
    builtCapabilities: ['Requisition flow', 'Candidate flow', 'Interview plan', 'Offer approval/send/accept'],
    keyWorkflows: ['Create requisition', 'Screen candidate', 'Schedule interview', 'Approve and accept offer'],
    dataObjects: ['Job requisition', 'Candidate', 'Interview', 'Offer'],
    governance: ['SoD on offer approval', 'Candidate privacy', 'Hiring manager scope'],
    commercialNext: ['Build ATS board, candidate portal, interview scorecards, and offer-to-onboarding handoff UI.'],
  },
  {
    id: 'onboarding',
    label: 'Onboarding',
    category: 'Talent',
    maturity: 'native-ui',
    backendRoot: '/onboarding',
    nativePath: '/admin/onboarding',
    summary: 'Admin onboarding operations and employee preboarding for plans, owner-group tasks, documents, IT provisioning, 30/60/90, buddy support, compliance, and probation.',
    personas: ['New Hire', 'Manager', 'HR Admin', 'IT', 'Finance', 'Security', 'Facilities'],
    builtCapabilities: ['Plan lifecycle', 'Task lifecycle', 'Preboarding checklist', 'Owner-group coordination', 'Employee task completion'],
    keyWorkflows: ['Launch onboarding plan', 'Assign owner tasks', 'Complete preboarding', 'Provision IT access', 'Manage probation readiness'],
    dataObjects: ['Onboarding plan', 'Onboarding task', 'Document evidence', 'Provisioning task', 'Probation checkpoint'],
    governance: ['Task ownership', 'Document checklist', 'Role-based visibility', 'Compliance evidence', 'Probation decision trail'],
    commercialNext: ['Add document storage packets, provisioning adapters, automated reminders, and manager probation decision forms.'],
  },
  {
    id: 'offboarding',
    label: 'Offboarding',
    category: 'Talent',
    maturity: 'native-ui',
    backendRoot: '/hr/offboarding',
    nativePath: '/admin/offboarding',
    summary: 'Admin exit operations and employee exit checklist for plans, owner-group tasks, asset return, access revocation confirmation, knowledge transfer, final settlement confirmation, and exit interviews.',
    personas: ['Departing Employee', 'Manager', 'HR Admin', 'IT', 'Finance', 'Security', 'Facilities'],
    builtCapabilities: ['Plan lifecycle', 'Task lifecycle', 'Reason-based exit templates', 'Owner-group coordination', 'Auto-initiation from termination', 'Employee task completion'],
    keyWorkflows: ['Launch exit plan', 'Auto-create plan on termination', 'Assign owner tasks', 'Confirm asset return and access revocation', 'Complete exit interview', 'Confirm final settlement'],
    dataObjects: ['Offboarding plan', 'Offboarding task', 'Asset return evidence', 'Access revocation confirmation', 'Final settlement confirmation'],
    governance: ['Task ownership', 'Reason categorization', 'Role-based visibility', 'Evidence trail', 'Auto-initiation tied to WorkerTerminated'],
    commercialNext: ['Add asset registry integration, automated reminders, and manager/HR exit sign-off workflows.'],
  },
  {
    id: 'performance',
    label: 'Performance',
    category: 'Talent',
    maturity: 'native-ui',
    backendRoot: '/performance',
    nativePath: '/admin/performance',
    summary: 'Review cycles, templates, SMART goals, 360 feedback, calibration, action plans, KPIs, analytics, and recognition.',
    personas: ['Employee', 'Manager', 'HR Admin'],
    builtCapabilities: ['Cycle setup', 'Notifications', 'SMART goals', '360 feedback', 'Calibration', 'Action plans', 'KPI formula engine'],
    keyWorkflows: ['Create cycle', 'Notify employees', 'Submit review and 360 feedback', 'Calibrate', 'Generate analytics'],
    dataObjects: ['Review cycle', 'Review', 'Goal', 'Feedback 360 response', 'Calibration session', 'Improvement plan', 'KPI'],
    governance: ['Anonymous thresholds', 'Bias checks', 'Score explainability', 'Performance privacy category'],
    commercialNext: ['Add visual review builder, scheduled reminders, continuous feedback stream, and richer manager inbox.'],
  },
  {
    id: 'learning',
    label: 'Learning',
    category: 'Talent',
    maturity: 'native-ui',
    backendRoot: '/learning',
    nativePath: '/admin/learning',
    summary: 'Courses, learning assignments, certifications, content packages, and SCORM/xAPI ready integration model.',
    personas: ['Employee', 'Manager', 'Learning Admin'],
    builtCapabilities: ['Course lifecycle', 'Assignment lifecycle', 'Certification records', 'Content package objects'],
    keyWorkflows: ['Publish course', 'Assign learning', 'Track completion', 'Renew certification'],
    dataObjects: ['Course', 'Learning assignment', 'Certification', 'Content package'],
    governance: ['Mandatory learning', 'Certification expiry', 'Manager visibility'],
    commercialNext: ['Build course catalog, learner transcript, manager compliance dashboard, and LMS adapter UI.'],
  },
  {
    id: 'skills-talent',
    label: 'Skills & Talent',
    category: 'Talent',
    maturity: 'native-ui',
    backendRoot: '/skills-talent',
    nativePath: '/admin/skills-talent',
    summary: 'Skill profiles, talent pools, career paths, succession plans, readiness, and career preferences.',
    personas: ['Employee', 'Manager', 'Talent Admin'],
    builtCapabilities: ['Skill profile model', 'Talent pool lifecycle', 'Career path', 'Succession plan'],
    keyWorkflows: ['Update skills', 'Nominate talent', 'Build succession slate', 'Track readiness'],
    dataObjects: ['Skill profile', 'Talent pool', 'Career path', 'Succession plan'],
    governance: ['Talent privacy', 'Manager scope', 'Readiness governance'],
    commercialNext: ['Create skills matrix, internal mobility board, succession heatmap, and career marketplace.'],
  },
  {
    id: 'engagement',
    label: 'Engagement',
    category: 'Talent',
    maturity: 'native-ui',
    backendRoot: '/engagement',
    nativePath: moduleOperationsPath('engagement'),
    summary: 'Surveys, survey responses, engagement feedback, recognition programs, and recognition records.',
    personas: ['Employee', 'Manager', 'HR Admin'],
    builtCapabilities: ['Survey lifecycle', 'Response collection', 'Recognition programs', 'Recognition approval/award'],
    keyWorkflows: ['Publish survey', 'Collect anonymous response', 'Analyze engagement', 'Award recognition'],
    dataObjects: ['Survey', 'Survey response', 'Recognition program', 'Recognition record'],
    governance: ['Anonymous reporting', 'Suppression thresholds', 'Recognition approval'],
    commercialNext: ['Build pulse survey builder, engagement heatmaps, sentiment dashboards, and recognition feed.'],
  },
  {
    id: 'employee-relations',
    label: 'Employee Relations',
    category: 'Compliance',
    maturity: 'native-ui',
    backendRoot: '/employee-relations',
    nativePath: '/admin/employee-relations',
    summary: 'Cases, investigations, disciplinary actions, accommodation cases, evidence review, appeal, and closure.',
    personas: ['ER Specialist', 'HR Admin', 'Legal', 'Manager'],
    builtCapabilities: ['ER case lifecycle', 'Investigation lifecycle', 'Disciplinary action workflow', 'Accommodation workflow'],
    keyWorkflows: ['Open case', 'Start investigation', 'Review evidence', 'Resolve or discipline', 'Close case'],
    dataObjects: ['ER case', 'Investigation', 'Disciplinary action', 'Accommodation case'],
    governance: ['Restricted case access', 'SoD on investigations', 'Legal privacy', 'Audit log'],
    commercialNext: ['Build restricted case workspace, evidence vault, interview log, and legal hold links.'],
  },
  {
    id: 'compliance',
    label: 'Compliance',
    category: 'Compliance',
    maturity: 'native-ui',
    backendRoot: '/compliance',
    nativePath: '/admin/compliance',
    summary: 'Policy documents, acknowledgements, legal holds, statutory reports, and compliance workflow states.',
    personas: ['Compliance Admin', 'HR Admin', 'Legal', 'Employee'],
    builtCapabilities: ['Policy publishing', 'Acknowledgement tracking', 'Legal hold', 'Statutory report objects'],
    keyWorkflows: ['Publish policy', 'Collect acknowledgement', 'Place legal hold', 'Generate statutory report'],
    dataObjects: ['Policy document', 'Policy acknowledgement', 'Legal hold', 'Statutory report'],
    governance: ['Immutability', 'Acknowledgement evidence', 'Legal hold restrictions'],
    commercialNext: ['Expose employee acknowledgement inbox and statutory report calendar.'],
  },
  {
    id: 'global-hr',
    label: 'Global HR',
    category: 'Compliance',
    maturity: 'native-ui',
    backendRoot: '/global-hr',
    nativePath: '/admin/global-hr',
    summary: 'Country rules, statutory leave types, works council consultations, work authorization, and global compliance context.',
    personas: ['Global HR', 'Legal', 'Compliance Admin'],
    builtCapabilities: ['Country rule sets', 'Statutory leave types', 'Works council cases', 'Work authorization cases'],
    keyWorkflows: ['Configure country rules', 'Validate work authorization', 'Run works council consultation'],
    dataObjects: ['Country rule set', 'Statutory leave type', 'Works council consultation', 'Work authorization case'],
    governance: ['Country localization', 'Works council blocking', 'Visa/work permit privacy'],
    commercialNext: ['Build country compliance cockpit and work authorization expiry alerts.'],
  },
  {
    id: 'country-policy',
    label: 'Country Policy',
    category: 'Compliance',
    maturity: 'native-ui',
    backendRoot: '/country-policy',
    nativePath: '/admin/country-policy',
    summary: 'Country policy packs, validation runs, impact simulations, approvals, publishing, and rollback.',
    personas: ['System Admin', 'Country HR', 'Compliance Admin'],
    builtCapabilities: ['Upload/validate/simulate/approve/publish', 'Impact simulation', 'Rollback-ready policy pack'],
    keyWorkflows: ['Validate country pack', 'Simulate impact', 'Approve and publish', 'Rollback if needed'],
    dataObjects: ['Country policy pack', 'Validation run', 'Impact simulation'],
    governance: ['Policy versioning', 'Approval workflow', 'Publication control'],
    commercialNext: ['Connect country packs directly to leave, payroll, attendance, and compliance calculations in UI.'],
  },
  {
    id: 'dei-analytics',
    label: 'DEI Analytics',
    category: 'Compliance',
    maturity: 'native-ui',
    backendRoot: '/dei-analytics',
    nativePath: '/admin/dei-analytics',
    summary: 'DEI reports, pay gap reports, pay equity reviews, attrition segment reports, and suppression thresholds.',
    personas: ['DEI Lead', 'HR Analytics', 'Legal'],
    builtCapabilities: ['DEI report lifecycle', 'Pay gap calculation', 'Pay equity review', 'Attrition reporting'],
    keyWorkflows: ['Generate DEI report', 'Review pay gap', 'Plan remediation', 'Publish suppressed analytics'],
    dataObjects: ['DEI report', 'Pay gap report', 'Pay equity review', 'Attrition segment report'],
    governance: ['Suppression threshold', 'Sensitive demographic data', 'Legal review'],
    commercialNext: ['Create equity dashboard with cohort filters, protected-data guardrails, and action tracking.'],
  },
  {
    id: 'hr-ai-governance',
    label: 'HR AI Governance',
    category: 'Compliance',
    maturity: 'native-ui',
    backendRoot: '/hr-ai-governance',
    nativePath: '/admin/hr-ai-governance',
    summary: 'AI use cases, model runs, bias tests, kill switches, risk classification, and human oversight.',
    personas: ['AI Governance', 'Legal', 'HR Admin'],
    builtCapabilities: ['AI use case lifecycle', 'Model run tracking', 'Bias tests', 'Kill switch'],
    keyWorkflows: ['Register AI use case', 'Run bias test', 'Approve oversight', 'Activate kill switch'],
    dataObjects: ['AI use case', 'Model run', 'Bias test', 'Kill switch'],
    governance: ['Risk tiering', 'Human oversight', 'Bias evidence', 'Auditability'],
    commercialNext: ['Build AI risk register and model-impact approval board.'],
  },
  {
    id: 'reporting',
    label: 'Reporting',
    category: 'Operations',
    maturity: 'native-ui',
    backendRoot: '/reporting',
    nativePath: '/admin/reports',
    summary: 'Workforce, reward, talent, service, and governance activity reporting.',
    personas: ['HR Analyst', 'Manager', 'HR Admin'],
    builtCapabilities: ['Report definition lifecycle', 'Execution queue', 'Schedules', 'Calculated fields'],
    keyWorkflows: ['Design report', 'Run report', 'Schedule delivery', 'Create calculated field'],
    dataObjects: ['Report definition', 'Report execution', 'Report schedule', 'Calculated field'],
    governance: ['Field-level access', 'Execution audit', 'Scheduled delivery controls'],
    commercialNext: ['Build report builder UI, saved dashboards, scheduled exports, and permissioned fields.'],
  },
  {
    id: 'service-delivery',
    label: 'HR Service Delivery',
    category: 'Operations',
    maturity: 'native-ui',
    backendRoot: '/hr-service-delivery',
    nativePath: '/admin/hr-service-delivery',
    summary: 'Service cases, case tasks, knowledge articles, catalog items, and SLA instances.',
    personas: ['Employee', 'HR Service Agent', 'Manager'],
    builtCapabilities: ['Service case lifecycle', 'Case task workflow', 'Knowledge article', 'Service catalog', 'SLA tracking'],
    keyWorkflows: ['Open HR case', 'Assign task', 'Resolve with knowledge article', 'Track SLA'],
    dataObjects: ['Service case', 'Case task', 'Knowledge article', 'Service catalog item', 'SLA instance'],
    governance: ['Case visibility', 'SLA escalation', 'Knowledge approval'],
    commercialNext: ['Create employee help center, agent queue, SLA dashboard, and knowledge search.'],
  },
  {
    id: 'scheduler',
    label: 'Automation Scheduler',
    category: 'Operations',
    maturity: 'native-ui',
    backendRoot: '/platform/scheduler',
    nativePath: '/admin/system-console/automation',
    summary: 'Scheduled jobs, reminders, run history, tenant overrides, enablement, and manual run controls.',
    personas: ['System Admin', 'HR Admin', 'Operations'],
    builtCapabilities: ['Scheduled job list', 'Tenant cron override', 'Enable and disable jobs', 'Manual run', 'Last run status'],
    keyWorkflows: ['Review automation health', 'Retune tenant schedule', 'Run a job now', 'Investigate failed runs'],
    dataObjects: ['Scheduled job', 'Schedule override', 'Job run', 'Reminder dispatch log'],
    governance: ['System actor permissions', 'Tenant isolation', 'Run ledger', 'Operational audit'],
    commercialNext: ['Add runbook links, stuck-run recovery, and job dependency visualization.'],
  },
  {
    id: 'contingent-workforce',
    label: 'Contingent Workforce',
    category: 'Operations',
    maturity: 'native-ui',
    backendRoot: '/contingent-workforce',
    nativePath: '/admin/contingent-workforce',
    summary: 'Contractor assignments, SOW engagements, rate cards, and misclassification assessments.',
    personas: ['Procurement', 'HR Admin', 'Manager', 'Legal'],
    builtCapabilities: ['Assignment lifecycle', 'SOW lifecycle', 'Rate card lifecycle', 'Misclassification assessment'],
    keyWorkflows: ['Activate contractor', 'Start SOW', 'Revise rate card', 'Clear or flag classification risk'],
    dataObjects: ['Contingent assignment', 'SOW engagement', 'Rate card', 'Misclassification assessment'],
    governance: ['Classification risk', 'Rate governance', 'Contract dates', 'Legal evidence'],
    commercialNext: ['Build contractor roster, SOW milestones, vendor export, and classification risk dashboard.'],
  },
  {
    id: 'wellbeing-eap',
    label: 'Wellbeing & EAP',
    category: 'Operations',
    maturity: 'native-ui',
    backendRoot: '/wellbeing-eap',
    nativePath: '/admin/wellbeing-eap',
    summary: 'EAP referrals, wellness programs, wellness claims, anonymous usage, and reimbursements.',
    personas: ['Employee', 'Benefits Admin', 'Wellbeing Lead'],
    builtCapabilities: ['EAP referral flow', 'Wellness program lifecycle', 'Claim workflow'],
    keyWorkflows: ['Refer to EAP', 'Enroll in wellness program', 'Submit claim', 'Reimburse approved claim'],
    dataObjects: ['EAP referral', 'Wellness program', 'Wellness claim'],
    governance: ['Anonymous usage', 'Health privacy', 'Claim approval'],
    commercialNext: ['Build confidential wellbeing portal and aggregated wellbeing insights.'],
  },
  {
    id: 'union-labor',
    label: 'Union & Labor',
    category: 'Compliance',
    maturity: 'native-ui',
    backendRoot: '/union-labor',
    nativePath: '/admin/union-labor',
    summary: 'Union recognition, grievances, collective bargaining sessions, arbitration, ratification, and closure.',
    personas: ['Labor Relations', 'Legal', 'HR Admin'],
    builtCapabilities: ['Union recognition lifecycle', 'Grievance workflow', 'Collective bargaining workflow'],
    keyWorkflows: ['Acknowledge grievance', 'Investigate', 'Arbitrate or resolve', 'Ratify agreement'],
    dataObjects: ['Union recognition', 'Grievance', 'Collective bargaining session'],
    governance: ['Legal timeline', 'Agreement ratification', 'Restricted labor records'],
    commercialNext: ['Create labor relations casebook, agreement library, and deadline calendar.'],
  },
];

export const moduleCategories = Array.from(new Set(commercialModules.map((module) => module.category)));

export function findCommercialModule(id: string | undefined) {
  return commercialModules.find((module) => module.id === id);
}
