import { Inject, Injectable, OnModuleInit } from '@nestjs/common';
import { FsmFramework } from '../../../platform/workflow/fsm-framework.js';

/**
 * Finite-state machine registrar for the CountryPolicyPack aggregate.
 *
 * States (28): DRAFT, UPLOADED, PARSING, VALIDATED, IMPACT_SIMULATION_REQUIRED,
 * IMPACT_SIMULATED, LEGAL_REVIEW_PENDING, PAYROLL_TAX_REVIEW_PENDING,
 * GLOBAL_HR_REVIEW_PENDING, BENEFITS_REVIEW_PENDING, ABSENCE_REVIEW_PENDING,
 * COMPLIANCE_REVIEW_PENDING, APPROVAL_PENDING, APPROVED,
 * SCHEDULED_FOR_PUBLICATION, PUBLISHED, SUPERSEDED, ROLLED_BACK, RETIRED,
 * REJECTED, QUARANTINED, VALIDATION_FAILED
 */
@Injectable()
export class CountryPolicyPackFsmRegistrar implements OnModuleInit {
  constructor(@Inject(FsmFramework) private readonly fsmFramework: FsmFramework) {}

  onModuleInit(): void {
    this.fsmFramework.register({
      aggregateType: 'CountryPolicyPack',
      states: [
        'DRAFT',
        'UPLOADED',
        'PARSING',
        'VALIDATED',
        'IMPACT_SIMULATION_REQUIRED',
        'IMPACT_SIMULATED',
        'LEGAL_REVIEW_PENDING',
        'PAYROLL_TAX_REVIEW_PENDING',
        'GLOBAL_HR_REVIEW_PENDING',
        'BENEFITS_REVIEW_PENDING',
        'ABSENCE_REVIEW_PENDING',
        'COMPLIANCE_REVIEW_PENDING',
        'APPROVAL_PENDING',
        'APPROVED',
        'SCHEDULED_FOR_PUBLICATION',
        'PUBLISHED',
        'SUPERSEDED',
        'ROLLED_BACK',
        'RETIRED',
        'REJECTED',
        'QUARANTINED',
        'VALIDATION_FAILED',
      ],
      actions: [
        'UploadCountryPolicyPack',
        'ParseCountryPolicyPack',
        'ValidateCountryPolicyPack',
        'RequireCountryPolicyPackImpactSimulation',
        'SimulateCountryPolicyPackImpact',
        'SubmitForLegalReview',
        'SubmitForPayrollTaxReview',
        'SubmitForGlobalHRReview',
        'SubmitForBenefitsReview',
        'SubmitForAbsenceReview',
        'SubmitForComplianceReview',
        'SubmitCountryPolicyPackForApproval',
        'ApproveCountryPolicyPack',
        'ScheduleCountryPolicyPackPublication',
        'PublishCountryPolicyPack',
        'SupersedeCountryPolicyPack',
        'RollbackCountryPolicyPack',
        'RetireCountryPolicyPack',
        'RejectCountryPolicyPack',
        'QuarantineCountryPolicyPack',
      ],
      transitions: [
        { action: 'UploadCountryPolicyPack', from: 'DRAFT', to: 'UPLOADED', eventName: 'CountryPolicyPackUploaded' },
        { action: 'ParseCountryPolicyPack', from: 'UPLOADED', to: 'PARSING', eventName: 'CountryPolicyPackParsed' },
        { action: 'ValidateCountryPolicyPack', from: 'PARSING', to: 'VALIDATED', eventName: 'CountryPolicyPackValidated' },
        { action: 'RequireCountryPolicyPackImpactSimulation', from: 'VALIDATED', to: 'IMPACT_SIMULATION_REQUIRED', eventName: 'ImpactSimulationRequired' },
        { action: 'SimulateCountryPolicyPackImpact', from: 'IMPACT_SIMULATION_REQUIRED', to: 'IMPACT_SIMULATED', eventName: 'CountryPolicyPackSimulated' },
        { action: 'SubmitForLegalReview', from: 'IMPACT_SIMULATED', to: 'LEGAL_REVIEW_PENDING', eventName: 'LegalReviewSubmitted' },
        { action: 'SubmitForLegalReview', from: 'PAYROLL_TAX_REVIEW_PENDING', to: 'LEGAL_REVIEW_PENDING', eventName: 'LegalReviewSubmitted' },
        { action: 'SubmitForLegalReview', from: 'GLOBAL_HR_REVIEW_PENDING', to: 'LEGAL_REVIEW_PENDING', eventName: 'LegalReviewSubmitted' },
        { action: 'SubmitForLegalReview', from: 'BENEFITS_REVIEW_PENDING', to: 'LEGAL_REVIEW_PENDING', eventName: 'LegalReviewSubmitted' },
        { action: 'SubmitForLegalReview', from: 'ABSENCE_REVIEW_PENDING', to: 'LEGAL_REVIEW_PENDING', eventName: 'LegalReviewSubmitted' },
        { action: 'SubmitForLegalReview', from: 'COMPLIANCE_REVIEW_PENDING', to: 'LEGAL_REVIEW_PENDING', eventName: 'LegalReviewSubmitted' },
        { action: 'SubmitForPayrollTaxReview', from: 'IMPACT_SIMULATED', to: 'PAYROLL_TAX_REVIEW_PENDING', eventName: 'PayrollTaxReviewSubmitted' },
        { action: 'SubmitForPayrollTaxReview', from: 'LEGAL_REVIEW_PENDING', to: 'PAYROLL_TAX_REVIEW_PENDING', eventName: 'PayrollTaxReviewSubmitted' },
        { action: 'SubmitForPayrollTaxReview', from: 'GLOBAL_HR_REVIEW_PENDING', to: 'PAYROLL_TAX_REVIEW_PENDING', eventName: 'PayrollTaxReviewSubmitted' },
        { action: 'SubmitForPayrollTaxReview', from: 'BENEFITS_REVIEW_PENDING', to: 'PAYROLL_TAX_REVIEW_PENDING', eventName: 'PayrollTaxReviewSubmitted' },
        { action: 'SubmitForPayrollTaxReview', from: 'ABSENCE_REVIEW_PENDING', to: 'PAYROLL_TAX_REVIEW_PENDING', eventName: 'PayrollTaxReviewSubmitted' },
        { action: 'SubmitForPayrollTaxReview', from: 'COMPLIANCE_REVIEW_PENDING', to: 'PAYROLL_TAX_REVIEW_PENDING', eventName: 'PayrollTaxReviewSubmitted' },
        { action: 'SubmitForGlobalHRReview', from: 'IMPACT_SIMULATED', to: 'GLOBAL_HR_REVIEW_PENDING', eventName: 'GlobalHRReviewSubmitted' },
        { action: 'SubmitForGlobalHRReview', from: 'LEGAL_REVIEW_PENDING', to: 'GLOBAL_HR_REVIEW_PENDING', eventName: 'GlobalHRReviewSubmitted' },
        { action: 'SubmitForGlobalHRReview', from: 'PAYROLL_TAX_REVIEW_PENDING', to: 'GLOBAL_HR_REVIEW_PENDING', eventName: 'GlobalHRReviewSubmitted' },
        { action: 'SubmitForGlobalHRReview', from: 'BENEFITS_REVIEW_PENDING', to: 'GLOBAL_HR_REVIEW_PENDING', eventName: 'GlobalHRReviewSubmitted' },
        { action: 'SubmitForGlobalHRReview', from: 'ABSENCE_REVIEW_PENDING', to: 'GLOBAL_HR_REVIEW_PENDING', eventName: 'GlobalHRReviewSubmitted' },
        { action: 'SubmitForGlobalHRReview', from: 'COMPLIANCE_REVIEW_PENDING', to: 'GLOBAL_HR_REVIEW_PENDING', eventName: 'GlobalHRReviewSubmitted' },
        { action: 'SubmitForBenefitsReview', from: 'IMPACT_SIMULATED', to: 'BENEFITS_REVIEW_PENDING', eventName: 'BenefitsReviewSubmitted' },
        { action: 'SubmitForBenefitsReview', from: 'LEGAL_REVIEW_PENDING', to: 'BENEFITS_REVIEW_PENDING', eventName: 'BenefitsReviewSubmitted' },
        { action: 'SubmitForBenefitsReview', from: 'PAYROLL_TAX_REVIEW_PENDING', to: 'BENEFITS_REVIEW_PENDING', eventName: 'BenefitsReviewSubmitted' },
        { action: 'SubmitForBenefitsReview', from: 'GLOBAL_HR_REVIEW_PENDING', to: 'BENEFITS_REVIEW_PENDING', eventName: 'BenefitsReviewSubmitted' },
        { action: 'SubmitForBenefitsReview', from: 'ABSENCE_REVIEW_PENDING', to: 'BENEFITS_REVIEW_PENDING', eventName: 'BenefitsReviewSubmitted' },
        { action: 'SubmitForBenefitsReview', from: 'COMPLIANCE_REVIEW_PENDING', to: 'BENEFITS_REVIEW_PENDING', eventName: 'BenefitsReviewSubmitted' },
        { action: 'SubmitForAbsenceReview', from: 'IMPACT_SIMULATED', to: 'ABSENCE_REVIEW_PENDING', eventName: 'AbsenceReviewSubmitted' },
        { action: 'SubmitForAbsenceReview', from: 'LEGAL_REVIEW_PENDING', to: 'ABSENCE_REVIEW_PENDING', eventName: 'AbsenceReviewSubmitted' },
        { action: 'SubmitForAbsenceReview', from: 'PAYROLL_TAX_REVIEW_PENDING', to: 'ABSENCE_REVIEW_PENDING', eventName: 'AbsenceReviewSubmitted' },
        { action: 'SubmitForAbsenceReview', from: 'GLOBAL_HR_REVIEW_PENDING', to: 'ABSENCE_REVIEW_PENDING', eventName: 'AbsenceReviewSubmitted' },
        { action: 'SubmitForAbsenceReview', from: 'BENEFITS_REVIEW_PENDING', to: 'ABSENCE_REVIEW_PENDING', eventName: 'AbsenceReviewSubmitted' },
        { action: 'SubmitForAbsenceReview', from: 'COMPLIANCE_REVIEW_PENDING', to: 'ABSENCE_REVIEW_PENDING', eventName: 'AbsenceReviewSubmitted' },
        { action: 'SubmitForComplianceReview', from: 'IMPACT_SIMULATED', to: 'COMPLIANCE_REVIEW_PENDING', eventName: 'ComplianceReviewSubmitted' },
        { action: 'SubmitForComplianceReview', from: 'LEGAL_REVIEW_PENDING', to: 'COMPLIANCE_REVIEW_PENDING', eventName: 'ComplianceReviewSubmitted' },
        { action: 'SubmitForComplianceReview', from: 'PAYROLL_TAX_REVIEW_PENDING', to: 'COMPLIANCE_REVIEW_PENDING', eventName: 'ComplianceReviewSubmitted' },
        { action: 'SubmitForComplianceReview', from: 'GLOBAL_HR_REVIEW_PENDING', to: 'COMPLIANCE_REVIEW_PENDING', eventName: 'ComplianceReviewSubmitted' },
        { action: 'SubmitForComplianceReview', from: 'BENEFITS_REVIEW_PENDING', to: 'COMPLIANCE_REVIEW_PENDING', eventName: 'ComplianceReviewSubmitted' },
        { action: 'SubmitForComplianceReview', from: 'ABSENCE_REVIEW_PENDING', to: 'COMPLIANCE_REVIEW_PENDING', eventName: 'ComplianceReviewSubmitted' },
        { action: 'SubmitCountryPolicyPackForApproval', from: 'IMPACT_SIMULATED', to: 'APPROVAL_PENDING', eventName: 'CountryPolicyPackApprovalSubmitted' },
        { action: 'SubmitCountryPolicyPackForApproval', from: 'LEGAL_REVIEW_PENDING', to: 'APPROVAL_PENDING', eventName: 'CountryPolicyPackApprovalSubmitted' },
        { action: 'SubmitCountryPolicyPackForApproval', from: 'PAYROLL_TAX_REVIEW_PENDING', to: 'APPROVAL_PENDING', eventName: 'CountryPolicyPackApprovalSubmitted' },
        { action: 'SubmitCountryPolicyPackForApproval', from: 'GLOBAL_HR_REVIEW_PENDING', to: 'APPROVAL_PENDING', eventName: 'CountryPolicyPackApprovalSubmitted' },
        { action: 'SubmitCountryPolicyPackForApproval', from: 'BENEFITS_REVIEW_PENDING', to: 'APPROVAL_PENDING', eventName: 'CountryPolicyPackApprovalSubmitted' },
        { action: 'SubmitCountryPolicyPackForApproval', from: 'ABSENCE_REVIEW_PENDING', to: 'APPROVAL_PENDING', eventName: 'CountryPolicyPackApprovalSubmitted' },
        { action: 'SubmitCountryPolicyPackForApproval', from: 'COMPLIANCE_REVIEW_PENDING', to: 'APPROVAL_PENDING', eventName: 'CountryPolicyPackApprovalSubmitted' },
        { action: 'ApproveCountryPolicyPack', from: 'APPROVAL_PENDING', to: 'APPROVED', eventName: 'CountryPolicyPackApproved' },
        { action: 'ScheduleCountryPolicyPackPublication', from: 'APPROVED', to: 'SCHEDULED_FOR_PUBLICATION', eventName: 'CountryPolicyPackScheduled' },
        { action: 'PublishCountryPolicyPack', from: 'SCHEDULED_FOR_PUBLICATION', to: 'PUBLISHED', eventName: 'CountryPolicyPackPublished' },
        { action: 'SupersedeCountryPolicyPack', from: 'PUBLISHED', to: 'SUPERSEDED', eventName: 'CountryPolicyPackSuperseded' },
        { action: 'RollbackCountryPolicyPack', from: 'PUBLISHED', to: 'ROLLED_BACK', eventName: 'CountryPolicyPackRolledBack' },
        { action: 'RollbackCountryPolicyPack', from: 'SUPERSEDED', to: 'ROLLED_BACK', eventName: 'CountryPolicyPackRolledBack' },
        { action: 'RetireCountryPolicyPack', from: 'SUPERSEDED', to: 'RETIRED', eventName: 'CountryPolicyPackRetired' },
        { action: 'RetireCountryPolicyPack', from: 'ROLLED_BACK', to: 'RETIRED', eventName: 'CountryPolicyPackRetired' },
        { action: 'RejectCountryPolicyPack', from: 'APPROVAL_PENDING', to: 'REJECTED', eventName: 'CountryPolicyPackRejected' },
        { action: 'QuarantineCountryPolicyPack', from: 'DRAFT', to: 'QUARANTINED', eventName: 'CountryPolicyPackQuarantined' },
        { action: 'QuarantineCountryPolicyPack', from: 'UPLOADED', to: 'QUARANTINED', eventName: 'CountryPolicyPackQuarantined' },
        { action: 'QuarantineCountryPolicyPack', from: 'PARSING', to: 'QUARANTINED', eventName: 'CountryPolicyPackQuarantined' },
        { action: 'QuarantineCountryPolicyPack', from: 'VALIDATED', to: 'QUARANTINED', eventName: 'CountryPolicyPackQuarantined' },
        { action: 'QuarantineCountryPolicyPack', from: 'IMPACT_SIMULATION_REQUIRED', to: 'QUARANTINED', eventName: 'CountryPolicyPackQuarantined' },
        { action: 'QuarantineCountryPolicyPack', from: 'IMPACT_SIMULATED', to: 'QUARANTINED', eventName: 'CountryPolicyPackQuarantined' },
        { action: 'QuarantineCountryPolicyPack', from: 'LEGAL_REVIEW_PENDING', to: 'QUARANTINED', eventName: 'CountryPolicyPackQuarantined' },
        { action: 'QuarantineCountryPolicyPack', from: 'PAYROLL_TAX_REVIEW_PENDING', to: 'QUARANTINED', eventName: 'CountryPolicyPackQuarantined' },
        { action: 'QuarantineCountryPolicyPack', from: 'GLOBAL_HR_REVIEW_PENDING', to: 'QUARANTINED', eventName: 'CountryPolicyPackQuarantined' },
        { action: 'QuarantineCountryPolicyPack', from: 'BENEFITS_REVIEW_PENDING', to: 'QUARANTINED', eventName: 'CountryPolicyPackQuarantined' },
        { action: 'QuarantineCountryPolicyPack', from: 'ABSENCE_REVIEW_PENDING', to: 'QUARANTINED', eventName: 'CountryPolicyPackQuarantined' },
        { action: 'QuarantineCountryPolicyPack', from: 'COMPLIANCE_REVIEW_PENDING', to: 'QUARANTINED', eventName: 'CountryPolicyPackQuarantined' },
        { action: 'QuarantineCountryPolicyPack', from: 'APPROVAL_PENDING', to: 'QUARANTINED', eventName: 'CountryPolicyPackQuarantined' },
        { action: 'QuarantineCountryPolicyPack', from: 'APPROVED', to: 'QUARANTINED', eventName: 'CountryPolicyPackQuarantined' },
        { action: 'QuarantineCountryPolicyPack', from: 'SCHEDULED_FOR_PUBLICATION', to: 'QUARANTINED', eventName: 'CountryPolicyPackQuarantined' },
        { action: 'QuarantineCountryPolicyPack', from: 'PUBLISHED', to: 'QUARANTINED', eventName: 'CountryPolicyPackQuarantined' },
      ],
      initialState: 'DRAFT',
      terminalStates: ['RETIRED', 'REJECTED', 'QUARANTINED', 'VALIDATION_FAILED'],
    });
  }
}
