exports.up = (pgm) => {
  pgm.createSchema('hr_platform');
  pgm.createSchema('hr_core');
  pgm.createSchema('hr_org');
  pgm.createSchema('hr_position');
  pgm.createSchema('hr_recruiting');
  pgm.createSchema('hr_onboarding');
  pgm.createSchema('hr_compensation');
  pgm.createSchema('hr_benefits');
  pgm.createSchema('hr_payroll');
  pgm.createSchema('hr_time');
  pgm.createSchema('hr_absence');
  pgm.createSchema('hr_performance');
  pgm.createSchema('hr_learning');
  pgm.createSchema('hr_skills');
  pgm.createSchema('hr_engagement');
  pgm.createSchema('hr_er');
  pgm.createSchema('hr_compliance');
  pgm.createSchema('hr_service_delivery');
  pgm.createSchema('hr_wfm');
  pgm.createSchema('hr_global');
  pgm.createSchema('hr_contingent');
  pgm.createSchema('hr_mobile');
  pgm.createSchema('hr_wellbeing');
  pgm.createSchema('hr_union');
  pgm.createSchema('hr_reporting');
  pgm.createSchema('hr_dei');
  pgm.createSchema('hr_country_policy');
  pgm.createSchema('hr_ai');
};

exports.down = (pgm) => {
  pgm.dropSchema('hr_ai', { cascade: true });
  pgm.dropSchema('hr_country_policy', { cascade: true });
  pgm.dropSchema('hr_dei', { cascade: true });
  pgm.dropSchema('hr_reporting', { cascade: true });
  pgm.dropSchema('hr_union', { cascade: true });
  pgm.dropSchema('hr_wellbeing', { cascade: true });
  pgm.dropSchema('hr_mobile', { cascade: true });
  pgm.dropSchema('hr_contingent', { cascade: true });
  pgm.dropSchema('hr_global', { cascade: true });
  pgm.dropSchema('hr_wfm', { cascade: true });
  pgm.dropSchema('hr_service_delivery', { cascade: true });
  pgm.dropSchema('hr_compliance', { cascade: true });
  pgm.dropSchema('hr_er', { cascade: true });
  pgm.dropSchema('hr_engagement', { cascade: true });
  pgm.dropSchema('hr_skills', { cascade: true });
  pgm.dropSchema('hr_learning', { cascade: true });
  pgm.dropSchema('hr_performance', { cascade: true });
  pgm.dropSchema('hr_absence', { cascade: true });
  pgm.dropSchema('hr_time', { cascade: true });
  pgm.dropSchema('hr_payroll', { cascade: true });
  pgm.dropSchema('hr_benefits', { cascade: true });
  pgm.dropSchema('hr_compensation', { cascade: true });
  pgm.dropSchema('hr_onboarding', { cascade: true });
  pgm.dropSchema('hr_recruiting', { cascade: true });
  pgm.dropSchema('hr_position', { cascade: true });
  pgm.dropSchema('hr_org', { cascade: true });
  pgm.dropSchema('hr_core', { cascade: true });
  pgm.dropSchema('hr_platform', { cascade: true });
};
